# Generated by Django 4.1 on 2024-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
