# Generated by Django 4.1 on 2024-10-09 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "博客详情", "verbose_name_plural": "博客详情"},
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name": "博客分类", "verbose_name_plural": "博客分类"},
        ),
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"verbose_name": "博客评论", "verbose_name_plural": "博客评论"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="博客作者",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.blogcategory",
                verbose_name="博客分类",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="博客内容"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="博客发布时间"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200, verbose_name="博客名称"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(max_length=200, verbose_name="博客分类名称"),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论者",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.blog",
                verbose_name="博客",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="content",
            field=models.TextField(verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
        ),
    ]
